
export const IMAGE = {
    offer: require('./offer.jpg'),
    grocery_placeholder: require('./grocery_placeholder.png'),
    empty_cart: require('./empty_cart.png'),
    account: require('./account.png'),
    wishlist: require('./wishlist.png'),
    place_holder_hr: require('./place_holder_hr.png'),
    gbnew: require('./gbnew.png'),
    splash_bg: require('./splash_bg.png'),
    splash_logo: require('./Splash_logo.png'),
    upper_curve: require('./upper_curve.png'),
    slide_menu_logo: require('./slide_menu_logo.png'),
    profile_pic: require('./profile_pic.png'),
    about_us: require('./about_us.png'),
    address: require('./address.png'),
    contact_us: require('./contact_us.png'),
    faq: require('./faq.png'),
    help: require('./help.png'),
    my_order: require('./my_order.png'),
    privacypolicy: require('./privacypolicy.png'),
    wishlist_menu: require('./wishlist_menu.png'),
    terms_condition: require('./terms_condition.png'),
    logout: require('./logout.png'),
    Login_circle: require('./Login_circle.png'),
    sign_in: require('./sign_in.png'),
     empty_list: require('./empty_list.png'),
}